# default coverage setting
coverage:
  range: 50..80 # below 50 is red, between 50-80 is yellow and above 80 is green
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 80% # coverage of the changes
        threshold: 1% # allow the coverage to drop by <threshold>%
    project:
      default:
        target: 80% # coverage of the project
ignore:
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*.pb.go"
  - go/ct/common/error.go # error file only declares error type without any logic
  - go/ct/driver/ # entry points, logic should be tested elsewhere.
  - go/examples # examples are not tested.
  - third_party/ # exclude all files in `third_party` directory
  - cpp/ # exclude all files in `cpp` directory
  - rust/ # exclude all files in `rust` directory
