version: "2"
linters:
  settings:
    staticcheck:
      initialisms: []
      dot-import-whitelist: []
      http-status-code-whitelist: []
      checks:
        - all
        # default ignored checks
        - "-ST1000" # Invalid regular expression.
        - "-ST1003" # Unsupported argument to functions in 'encoding/binary'.
        - "-ST1016" # Trapping a signal that cannot be trapped.
        - "-ST1020" # Using an invalid host:port pair with a 'net.Listen'-related function.
        - "-ST1021" # Using 'bytes.Equal' to compare two 'net.IP'.
        - "-ST1022" #

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
