// Copyright (c) 2025 Sonic Operations Ltd
//
// Use of this software is governed by the Business Source License included
// in the LICENSE file and at soniclabs.com/bsl11.
//
// Change Date: 2028-4-16
//
// On the date above, in accordance with the Business Source License, use of
// this software will be governed by the GNU Lesser General Public License v3

// Code generated by MockGen. DO NOT EDIT.
// Source: world_state.go
//
// Generated by this command:
//
//	mockgen -source world_state.go -destination world_state_mock.go -package tosca
//

// Package tosca is a generated GoMock package.
package tosca

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterpreterContext is a mock of InterpreterContext interface.
type MockInterpreterContext struct {
	ctrl     *gomock.Controller
	recorder *MockInterpreterContextMockRecorder
	isgomock struct{}
}

// MockInterpreterContextMockRecorder is the mock recorder for MockInterpreterContext.
type MockInterpreterContextMockRecorder struct {
	mock *MockInterpreterContext
}

// NewMockInterpreterContext creates a new mock instance.
func NewMockInterpreterContext(ctrl *gomock.Controller) *MockInterpreterContext {
	mock := &MockInterpreterContext{ctrl: ctrl}
	mock.recorder = &MockInterpreterContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterpreterContext) EXPECT() *MockInterpreterContextMockRecorder {
	return m.recorder
}

// AccessAccount mocks base method.
func (m *MockInterpreterContext) AccessAccount(arg0 Address) AccessStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessAccount", arg0)
	ret0, _ := ret[0].(AccessStatus)
	return ret0
}

// AccessAccount indicates an expected call of AccessAccount.
func (mr *MockInterpreterContextMockRecorder) AccessAccount(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessAccount", reflect.TypeOf((*MockInterpreterContext)(nil).AccessAccount), arg0)
}

// AccessStorage mocks base method.
func (m *MockInterpreterContext) AccessStorage(arg0 Address, arg1 Key) AccessStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessStorage", arg0, arg1)
	ret0, _ := ret[0].(AccessStatus)
	return ret0
}

// AccessStorage indicates an expected call of AccessStorage.
func (mr *MockInterpreterContextMockRecorder) AccessStorage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessStorage", reflect.TypeOf((*MockInterpreterContext)(nil).AccessStorage), arg0, arg1)
}

// EmitLog mocks base method.
func (m *MockInterpreterContext) EmitLog(arg0 Log) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitLog", arg0)
}

// EmitLog indicates an expected call of EmitLog.
func (mr *MockInterpreterContextMockRecorder) EmitLog(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitLog", reflect.TypeOf((*MockInterpreterContext)(nil).EmitLog), arg0)
}

// GetBalance mocks base method.
func (m *MockInterpreterContext) GetBalance(arg0 Address) Value {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0)
	ret0, _ := ret[0].(Value)
	return ret0
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockInterpreterContextMockRecorder) GetBalance(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockInterpreterContext)(nil).GetBalance), arg0)
}

// GetBlockHash mocks base method.
func (m *MockInterpreterContext) GetBlockHash(arg0 int64) Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", arg0)
	ret0, _ := ret[0].(Hash)
	return ret0
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockInterpreterContextMockRecorder) GetBlockHash(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockInterpreterContext)(nil).GetBlockHash), arg0)
}

// GetCode mocks base method.
func (m *MockInterpreterContext) GetCode(arg0 Address) Code {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", arg0)
	ret0, _ := ret[0].(Code)
	return ret0
}

// GetCode indicates an expected call of GetCode.
func (mr *MockInterpreterContextMockRecorder) GetCode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockInterpreterContext)(nil).GetCode), arg0)
}

// GetCodeHash mocks base method.
func (m *MockInterpreterContext) GetCodeHash(arg0 Address) Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeHash", arg0)
	ret0, _ := ret[0].(Hash)
	return ret0
}

// GetCodeHash indicates an expected call of GetCodeHash.
func (mr *MockInterpreterContextMockRecorder) GetCodeHash(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeHash", reflect.TypeOf((*MockInterpreterContext)(nil).GetCodeHash), arg0)
}

// GetCodeSize mocks base method.
func (m *MockInterpreterContext) GetCodeSize(arg0 Address) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeSize", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetCodeSize indicates an expected call of GetCodeSize.
func (mr *MockInterpreterContextMockRecorder) GetCodeSize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeSize", reflect.TypeOf((*MockInterpreterContext)(nil).GetCodeSize), arg0)
}

// GetCommittedStorage mocks base method.
func (m *MockInterpreterContext) GetCommittedStorage(addr Address, key Key) Word {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommittedStorage", addr, key)
	ret0, _ := ret[0].(Word)
	return ret0
}

// GetCommittedStorage indicates an expected call of GetCommittedStorage.
func (mr *MockInterpreterContextMockRecorder) GetCommittedStorage(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommittedStorage", reflect.TypeOf((*MockInterpreterContext)(nil).GetCommittedStorage), addr, key)
}

// GetNonce mocks base method.
func (m *MockInterpreterContext) GetNonce(arg0 Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", arg0)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockInterpreterContextMockRecorder) GetNonce(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockInterpreterContext)(nil).GetNonce), arg0)
}

// GetStorage mocks base method.
func (m *MockInterpreterContext) GetStorage(arg0 Address, arg1 Key) Word {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorage", arg0, arg1)
	ret0, _ := ret[0].(Word)
	return ret0
}

// GetStorage indicates an expected call of GetStorage.
func (mr *MockInterpreterContextMockRecorder) GetStorage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorage", reflect.TypeOf((*MockInterpreterContext)(nil).GetStorage), arg0, arg1)
}

// GetTransientStorage mocks base method.
func (m *MockInterpreterContext) GetTransientStorage(arg0 Address, arg1 Key) Word {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransientStorage", arg0, arg1)
	ret0, _ := ret[0].(Word)
	return ret0
}

// GetTransientStorage indicates an expected call of GetTransientStorage.
func (mr *MockInterpreterContextMockRecorder) GetTransientStorage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransientStorage", reflect.TypeOf((*MockInterpreterContext)(nil).GetTransientStorage), arg0, arg1)
}

// HasSelfDestructed mocks base method.
func (m *MockInterpreterContext) HasSelfDestructed(addr Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSelfDestructed", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasSelfDestructed indicates an expected call of HasSelfDestructed.
func (mr *MockInterpreterContextMockRecorder) HasSelfDestructed(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSelfDestructed", reflect.TypeOf((*MockInterpreterContext)(nil).HasSelfDestructed), addr)
}

// IsAddressInAccessList mocks base method.
func (m *MockInterpreterContext) IsAddressInAccessList(addr Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAddressInAccessList", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAddressInAccessList indicates an expected call of IsAddressInAccessList.
func (mr *MockInterpreterContextMockRecorder) IsAddressInAccessList(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAddressInAccessList", reflect.TypeOf((*MockInterpreterContext)(nil).IsAddressInAccessList), addr)
}

// IsNewContract mocks base method.
func (m *MockInterpreterContext) IsNewContract(arg0 Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNewContract", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNewContract indicates an expected call of IsNewContract.
func (mr *MockInterpreterContextMockRecorder) IsNewContract(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNewContract", reflect.TypeOf((*MockInterpreterContext)(nil).IsNewContract), arg0)
}

// IsSlotInAccessList mocks base method.
func (m *MockInterpreterContext) IsSlotInAccessList(addr Address, key Key) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlotInAccessList", addr, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsSlotInAccessList indicates an expected call of IsSlotInAccessList.
func (mr *MockInterpreterContextMockRecorder) IsSlotInAccessList(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlotInAccessList", reflect.TypeOf((*MockInterpreterContext)(nil).IsSlotInAccessList), addr, key)
}

// SelfDestruct mocks base method.
func (m *MockInterpreterContext) SelfDestruct(address, beneficiary Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfDestruct", address, beneficiary)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SelfDestruct indicates an expected call of SelfDestruct.
func (mr *MockInterpreterContextMockRecorder) SelfDestruct(address, beneficiary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfDestruct", reflect.TypeOf((*MockInterpreterContext)(nil).SelfDestruct), address, beneficiary)
}

// SetBalance mocks base method.
func (m *MockInterpreterContext) SetBalance(arg0 Address, arg1 Value) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBalance", arg0, arg1)
}

// SetBalance indicates an expected call of SetBalance.
func (mr *MockInterpreterContextMockRecorder) SetBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBalance", reflect.TypeOf((*MockInterpreterContext)(nil).SetBalance), arg0, arg1)
}

// SetStorage mocks base method.
func (m *MockInterpreterContext) SetStorage(arg0 Address, arg1 Key, arg2 Word) StorageStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStorage", arg0, arg1, arg2)
	ret0, _ := ret[0].(StorageStatus)
	return ret0
}

// SetStorage indicates an expected call of SetStorage.
func (mr *MockInterpreterContextMockRecorder) SetStorage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStorage", reflect.TypeOf((*MockInterpreterContext)(nil).SetStorage), arg0, arg1, arg2)
}

// SetTransientStorage mocks base method.
func (m *MockInterpreterContext) SetTransientStorage(arg0 Address, arg1 Key, arg2 Word) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTransientStorage", arg0, arg1, arg2)
}

// SetTransientStorage indicates an expected call of SetTransientStorage.
func (mr *MockInterpreterContextMockRecorder) SetTransientStorage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTransientStorage", reflect.TypeOf((*MockInterpreterContext)(nil).SetTransientStorage), arg0, arg1, arg2)
}
